#!/bin/bash

set -e

source /usr/local/lib/cloud-inceptor/common

if [[ $(whoami) != root ]]; then
    echo -e "\nThis script needs to be run as root.\n"
    exit 1
fi

network_apply_docker_user_forward
