#!/bin/bash

set -exo pipefail

SCRIPT_HOME=$(cd $(dirname "$(ls -l $0 | awk '{ print $NF }')") && pwd)
source $SCRIPT_HOME/common

[[ ! -e /usr/local/etc/.smtp_installed ]] || exit 0

if [[ -z $config_smtp_internal_smtp_port ]]; then
  echo "Skipping SMTP setup as no internal SMTP port configuration found."
  exit 0
fi

mkdir -p /var/mail
chmod 777 /var/mail

sed -i "s|^HELO_reject =.*$|HELO_reject = False|" /etc/postfix-policyd-spf-python/policyd-spf.conf
sed -i "s|^Mail_From_reject =.*$|Mail_From_reject = False|" /etc/postfix-policyd-spf-python/policyd-spf.conf

sed -i "s|\(default_transport =.*\)|#\1|" /etc/postfix/main.cf
sed -i "s|\(relay_transport =.*\)|#\1|" /etc/postfix/main.cf

postconf -e "compatibility_level=2"

postconf -e "myhostname = $(hostname)"
postconf -e "mydomain = $config_server_fqdn"
postconf -e "myorigin = \$mydomain"
postconf -e "masquerade_domains = \$mydomain"
postconf -e "mydestination = \$myhostname, \$mydomain, localhost.localdomain, localhost"
postconf -e "mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128 $config_smtp_networks"

if [[ -n $config_smtp_relay_host \
  && -n $config_smtp_relay_port \
  && -n $config_smtp_relay_api_key ]]; then

  postconf -e "relayhost = [$config_smtp_relay_host]:$config_smtp_relay_port"
  postconf -e "smtp_tls_security_level = encrypt"
  postconf -e "smtp_sasl_auth_enable = yes"
  postconf -e "smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd"
  postconf -e "smtp_sasl_security_options = noanonymous"
  postconf -e "header_size_limit = 4096000"
fi

postconf -e "mail_spool_directory = /var/mail"
postconf -e "home_mailbox = .mail/"

postconf -e "policy-spf_time_limit = 3600s"
postconf -e "smtpd_recipient_restrictions = permit_mynetworks,permit_sasl_authenticated,reject_unauth_destination,check_policy_service unix:private/policy-spf"

s="${config_smtp_internal_smtp_port}      inet  n       -       y       -       -       smtpd"
grep -q "^${config_smtp_internal_smtp_port}\s" /etc/postfix/master.cf \
  && sed -i ":a;N;\$!ba;s|10025.*smtpd|$s|g" /etc/postfix/master.cf \
  || echo -e "$s" >> /etc/postfix/master.cf

s="policy-spf  unix  -       n       n       -       -       spawn\n  user=nobody argv=/usr/bin/policyd-spf"
grep -q "^policy-spf\s" /etc/postfix/master.cf \
  && sed -i ":a;N;\$!ba;s|policy-spf.*policyd-spf|$s|g" /etc/postfix/master.cf \
  || echo -e "$s" >> /etc/postfix/master.cf

echo "[$config_smtp_relay_host]:$config_smtp_relay_port apikey:$config_smtp_relay_api_key" > /etc/postfix/sasl_passwd
postmap /etc/postfix/sasl_passwd
rm -f /etc/postfix/sasl_passwd

chmod 600 /etc/postfix/sasl_passwd.db

systemctl enable postfix
systemctl restart postfix

set +ex
touch /usr/local/etc/.smtp_installed
