#!/bin/bash

set -e

SCRIPT_HOME=$(cd $(dirname "$(ls -l $0 | awk '{ print $NF }')") && pwd)
source $SCRIPT_HOME/common

if [[ -z "$1" ]]; then
  echo -e "\nUsage: delete_vpn_user user\n"
  exit 1
fi

if [[ `whoami` != "root" ]]; then 
  echo -e "\nThis script needs to be run as root.\n"
  exit 1
fi

user=$1
userdel $user > /dev/null 2>&1
rm -fr /data/users/home/$user

strongswan_remove_user_creds "$user"
rm -f /etc/ipsec.d/private/${user}.{der,pem}
rm -f /etc/ipsec.d/certs/${user}.{der,pem}

if [[ -e /etc/apache2 ]]; then
  APACHE_USER_CONFIG=/data/users/etc/apache2
  rm -f ${APACHE_USER_CONFIG}/$user.conf
  systemctl restart apache2
fi

sed -i "/^AllowUsers $user$/d" /etc/ssh/sshd_config
service sshd restart

# Backup all system user files
cp /etc/passwd /data/users/etc
cp /etc/shadow /data/users/etc
cp /etc/group /data/users/etc
cp /etc/gshadow /data/users/etc
cp /etc/ssh/sshd_config /data/users/etc/ssh

set +e
