#!/bin/bash

set -e

source /usr/local/lib/cloud-inceptor/common

if [[ `whoami` != "root" ]]; then 
  echo -e "\nThis script needs to be run as root.\n"
  exit 1
fi

num_connected_clients=$(strongswan_count_established_sas)

mkdir -p /var/log/strongswan
echo $num_connected_clients > /var/log/strongswan/numvpnusers

shutdown_counter=/var/log/strongswan/shutdown_countdown

counter=$([[ -e $shutdown_counter ]] && cat $shutdown_counter || echo 10)
if [[ $num_connected_clients -eq 0 ]]; then
  counter=$((counter-1))
else
  counter=10
fi
if [[ $counter -gt 0 ]]; then
  echo "$counter" > $shutdown_counter
else
  rm $shutdown_counter
  echo $(date +"%Y-%m-%d %H:%M:%S")' Shutting down instance due to inactivity...' \
    >> /var/log/strongswan-status.log
  shutdown now
fi
