#!/bin/bash

set -e

if [[ `whoami` != "root" ]]; then 
  echo -e "\nThis script needs to be run as root.\n"
  exit 1
fi

openvpn_status=$(/usr/bin/expect << "---EOF"
  spawn /bin/nc localhost 7505
  set timeout 10
  expect "OpenVPN Management Interface"
  send "status 3\r"
  expect "END"
  send "exit\r\r"
---EOF
)
num_connected_clients=$(echo -e "$openvpn_status" | grep -e ^CLIENT_LIST | wc -l)
echo $num_connected_clients > /var/run/openvpn/numvpnusers

shutdown_counter=/var/run/openvpn/shutdown_countdown

counter=$([[ -e $shutdown_counter ]] && cat $shutdown_counter || echo 10)
if [[ $num_connected_clients -eq 0 ]]; then
  counter=$((counter-1))
else
  counter=10
fi
if [[ $counter -gt 0 ]]; then
  echo "$counter" > $shutdown_counter
else
  rm $shutdown_counter
  echo $(date +"%Y-%m-%d %H:%M:%S")' Shutting down instance due to inactivity...' >> /var/log/openvpn-status.log
  shutdown now
fi
