name: Build dev Bastion Images
concurrency: dev

on:
  workflow_dispatch:
  push:
    branches: [ dev ]
    paths:
    - 'image/build/**'
    - 'image/packer/**'
    - 'image/scripts/**'
    - 'image/www/**'

jobs:

  #
  # AWS Dev Build & Publish
  #

  create-version:
    runs-on: ubuntu-latest
    outputs: 
      version: ${{steps.create-dev-version.outputs.version}}

    defaults:
      run:
        shell: bash

    steps:

    - name: Create dev version
      id: create-dev-version
      run: |
        DEV_BUILD=D.$(date -u '+%y%m%d%H%M%S')
        echo $DEV_BUILD
        echo "version=${DEV_BUILD}" >> $GITHUB_OUTPUT

  build-aws-image:
    needs: create-version
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: image

    # Setup environment for build
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      DEV_BUILD: ${{ needs.create-version.outputs.version }}

    steps:
      
    - name: Checkout
      uses: actions/checkout@v3

    - name: Run build
      run: |        
        build/delete-aws-images.sh 'D.*' all &
        build/build-aws-image.sh us-east-1 $DEV_BUILD

    - name: Publish image
      run: |
        build/publish-aws-image.sh us-east-1 $DEV_BUILD "us-east-2 us-west-2 eu-west-1 eu-west-2 eu-central-2 af-south-1 ap-south-1 ap-southeast-1"

  trigger-dependent-builds:
    needs: 
    - build-aws-image

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:

    - name: Trigger vpn-server build
      uses: benc-uk/workflow-dispatch@v1
      with:
        repo: appbricks/spacenode-cookbook
        ref: dev
        workflow: MyCS SpaceNode Cookbook and SDK (appbricks/spacenode-cookbook:dev) CLI
        token: ${{ secrets.GH_TOKEN }}
