name: Build Bastion Images (dev)
concurrency: build-image-dev

on:
  workflow_dispatch:
  push:
    branches: [dev]
    paths:
      - "image/build/**"
      - "image/packer/**"
      - "image/scripts/**"
      - "image/www/**"

permissions:
  contents: read
  actions: write

jobs:
  create-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.create-dev-version.outputs.version }}
      bastion_image_name: ${{ steps.create-dev-version.outputs.bastion_image_name }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Create dev version
        id: create-dev-version
        run: |
          DEV_BUILD=D.$(date -u '+%y%m%d%H%M%S')
          echo "version=${DEV_BUILD}" >> "$GITHUB_OUTPUT"
          echo "bastion_image_name=mycs-node-image_${DEV_BUILD}" >> "$GITHUB_OUTPUT"
          echo "Dev bastion version: ${DEV_BUILD} → mycs-node-image_${DEV_BUILD}"

  build-aws-image:
    needs: create-version
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: image

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      DEV_BUILD: ${{ needs.create-version.outputs.version }}
      IS_DEV_BUILD: yes

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run build
        run: |
          build/delete-aws-images.sh 'D.*' all &
          build/build-aws-image.sh us-east-1 "$DEV_BUILD"

      - name: Publish image
        run: |
          build/publish-aws-image.sh us-east-1 "$DEV_BUILD" \
            "us-east-2 us-west-2 eu-west-1 eu-west-2 eu-central-2 af-south-1 ap-south-1 ap-southeast-1"

  trigger-vpn-node-builder:
    needs:
      - create-version
      - build-aws-image
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Trigger vpn-node-builder Docker build
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-vpn-node-builder-dev.yml
          ref: ${{ github.ref }}
          token: ${{ github.token }}
          inputs: |
            {
              "bastion_image_name": "${{ needs.create-version.outputs.bastion_image_name }}"
            }
